import React from 'react';

//GENERAL ICONS
import VisibilityOnSvg from '../../../../public/static/Svg/visibility-on.svg';
import VisibiityOffSvg from '../../../../public/static/Svg/visibility-off.svg';
import ArrowBackSvg from '../../../../public/static/Svg/arrow-back.svg';
export const VisibiityOnIcon = () => <VisibilityOnSvg />;
export const VisibiityOffIcon = () => <VisibiityOffSvg />;
export const ArrowBackIcon = () => <ArrowBackSvg />;

// Place Finder
import HamburgerSvg from '../../../../public/static/Svg/sidebar/hamburger.svg';
import UsersSvg from '../../../../public/static/Svg/sidebar/users.svg';
import LocationSvg from '../../../../public/static/Svg/sidebar/location.svg';
import DeactiveSvg from '../../../../public/static/Svg/visibility-off.svg';
import ActiveSvg from '../../../../public/static/Svg/visibility-on.svg';
import EditSvg from '../../../../public/static/Svg/Actions/edit-icon.svg';
import DeleteSvg from '../../../../public/static/Svg/Actions/delete-icon.svg';
import AddIconSvg from '../../../../public/static/Svg/Gallery/add-icon.svg';
import DoneSvg from '../../../../public/static/Svg/Gallery/DoneIcon.svg';
import BusinessSvg from '../../../../public/static/Svg/sidebar/business.svg';
import CuisineSvg from '../../../../public/static/Svg/sidebar/cuisine.svg';
import FoodTypeSvg from '../../../../public/static/Svg/sidebar/food-type.svg';
import DoubleArrowSvg from '../../../../public/static/Svg/double-arrow.svg';

export const HamburgerIcon = () => <HamburgerSvg />;
export const UsersIcon = () => <UsersSvg />;
export const LocationIcon = () => <LocationSvg />;
export const BusinessIcon = () => <BusinessSvg />;
export const CuisineIcon = () => <CuisineSvg />;
export const FoodTypeIcon = () => <FoodTypeSvg />;
export const DeleteIcon = () => <DeleteSvg />;
export const VisibilityOnIcon = () => <ActiveSvg />;
export const VisibilityOffIcon = () => <DeactiveSvg />;
export const EditIcon = () => <EditSvg />;
export const AddIcon = () => <AddIconSvg />;
export const DoneIcon = () => <DoneSvg />;
export const DoubleArrowIcon = () => <DoubleArrowSvg />;

// DIATERY
import WeedFreeSvg from '../../../../public/static/Svg/diatery/weed-free.svg';
import AlcoholFreeSvg from '../../../../public/static/Svg/diatery/alcohol-free.svg';
import VeganFreeSvg from '../../../../public/static/Svg/diatery/vegan-free.svg';
import MeetFreeSvg from '../../../../public/static/Svg/diatery/meet-free.svg';

export const WeedFreeIcon = () => <WeedFreeSvg />;
export const AlcoholFreeIcon = () => <AlcoholFreeSvg />;
export const VeganFreeIcon = () => <VeganFreeSvg />;
export const MeetFreeIcon = () => <MeetFreeSvg />;

import GlutinFreeSvg from '../../../../public/static/Svg/diatery/Gluten-free.svg';
import HalalFriendlySvg from '../../../../public/static/Svg/diatery/Halal-friendly.svg';
import VeganFriendlySvg from '../../../../public/static/Svg/diatery/Vegan-friendly.svg';
import VegetarianFriendlySvg from '../../../../public/static/Svg/diatery/Vegetarian-friendly.svg';
export const GlutinFreeIcon = () => <GlutinFreeSvg />;
export const HalalFriendlyIcon = () => <HalalFriendlySvg />;
export const VeganFriendlyIcon = () => <VeganFriendlySvg />;
export const VegetarianFriendlyIcon = () => <VegetarianFriendlySvg />;

//BUSINESS SERVICES
import DisableSvg from '../../../../public/static/Svg/business-service/disable.svg';
import DogsSvg from '../../../../public/static/Svg/business-service/dogs.svg';
import VegansSvg from '../../../../public/static/Svg/business-service/vegans.svg';
import WeedSvg from '../../../../public/static/Svg/business-service/weed.svg';
import HalalSvg from '../../../../public/static/Svg/business-service/halal.svg';

import BigDogFriendlySvg from '../../../../public/static/Svg/business-service/Big-dog-friendly.svg';
import SmallDogFriendlySvg from '../../../../public/static/Svg/business-service/Small-dog-friendly.svg';
import WheelChairFriendlySvg from '../../../../public/static/Svg/business-service/Wheelchair-friendly.svg';

export const BigDogFriendlyIcon = () => <BigDogFriendlySvg />;
export const SmallDogFriendlyIcon = () => <SmallDogFriendlySvg />;
export const WheelChairFriendlyIcon = () => <WheelChairFriendlySvg />;

export const DisableIcon = () => <DisableSvg />;
export const DogsIcon = () => <DogsSvg />;
export const VegansIcon = () => <VegansSvg />;
export const WeedIcon = () => <WeedSvg />;
export const HalalIcon = () => <HalalSvg />;

// -------------------------------------------------------------------------------------
// TAABEH
import ProfileSvg from '../../../../public/static/Svg/profile.svg';
import LogoutSvg from '../../../../public/static/Svg/logout.svg';
import BellSvg from '../../../../public/static/Svg/bell-icon.svg';
import HomeSvg from '../../../../public/static/Svg/sidebar/home.svg';
import GamesSvg from '../../../../public/static/Svg/sidebar/games.svg';
import ReelsSvg from '../../../../public/static/Svg/sidebar/reels.svg';
import SettingsSvg from '../../../../public/static/Svg/sidebar/settings.svg';
import RankingSvg from '../../../../public/static/Svg/sidebar/ranking.svg';
import UploadImageSvg from '../../../../public/static/Svg/image-upload.svg';
import GlassSvg from '../../../../public/static/Svg/water-glass.svg';
import CoffeeSvg from '../../../../public/static/Svg/coffee.svg';
import ParkingSvg from '../../../../public/static/Svg/parking.svg';
import ToiletSvg from '../../../../public/static/Svg/toilet.svg';
import VestSvg from '../../../../public/static/Svg/vest.svg';
import WhistleSvg from '../../../../public/static/Svg/whistle.svg';
import PlusSvg from '../../../../public/static/Svg/plus.svg';
import MinusSvg from '../../../../public/static/Svg/minus.svg';
import UserSvg from '../../../../public/static/Svg/user-icon.svg';
import MatchesSvg from '../../../../public/static/Svg/matches.svg';
import GoalsSvg from '../../../../public/static/Svg/goals.svg';
import RedSvg from '../../../../public/static/Svg/red.svg';
import YellowSvg from '../../../../public/static/Svg/yellow.svg';
import AssistSvg from '../../../../public/static/Svg/assists.svg';

export const ProfileIcon = () => <ProfileSvg />;
export const LogoutIcon = () => <LogoutSvg />;
export const BellIcon = () => <BellSvg />;
export const HomeIcon = () => <HomeSvg />;
export const GamesIcon = () => <GamesSvg />;
export const ReelsIcon = () => <ReelsSvg />;
export const SettingsIcon = () => <SettingsSvg />;
export const RankingIcon = () => <RankingSvg />;
export const UploadImageIcon = () => <UploadImageSvg />;
export const GlassIcon = () => <GlassSvg />;
export const CoffeeIcon = () => <CoffeeSvg />;
export const ToiletIcon = () => <ToiletSvg />;
export const ParkingIcon = () => <ParkingSvg />;
export const VestIcon = () => <VestSvg />;
export const WhistleIcon = () => <WhistleSvg />;
export const PlusIcon = () => <PlusSvg />;
export const MinusIcon = () => <MinusSvg />;
export const UserIcon = () => <UserSvg />;
export const MatchesIcon = () => <MatchesSvg />;
export const GoalsIcon = () => <GoalsSvg />;
export const RedIcon = () => <RedSvg />;
export const YellowIcon = () => <YellowSvg />;
export const AssistsIcon = () => <AssistSvg />;

// OTHERS
import CartSvg from '../../../../public/static/images/sample.svg';
import CalendersIcon from '../../../../public/static/Svg/Icon metro-calendar.svg';
import ContactsIcon from '../../../../public/static/Svg/Icon metro-users.svg';
import AnalyticIcon from '../../../../public/static/Svg/Icon ionic-md-business.svg';
import PublishIcon from '../../../../public/static/Svg/Icon material-share.svg';
import TelegramSvg from '../../../../public/static/Svg/telegram.svg';
import SkypeSvg from '../../../../public/static/Svg/skype.svg';
import WhatsappSvg from '../../../../public/static/Svg/whatsapp.svg';
import MessengerSvg from '../../../../public/static/Svg/messenger.svg';
import FacebookSvg from '../../../../public/static/Svg/facebook.svg';
import InstaSvg from '../../../../public/static/Svg/insta.svg';
import LinkedInSvg from '../../../../public/static/Svg/linkedIn.svg';
import TwitterSvg from '../../../../public/static/Svg/twitter.svg';
import CameraPng from '../../../../public/static/images/camera.svg';
import CrossSvg from '../../../../public/static/images/cross.svg';
import UploadSvg from '../../../../public/static/Svg/upload.svg';
import EditSvgOrange from '../../../../public/static/Svg/edit.svg';
import EditDetailsSvg from '../../../../public/static/Svg/edit-details.svg';
import ServiceSvg from '../../../../public/static/Svg/service.svg';
import StaffSvg from '../../../../public/static/Svg/staff.svg';
import DateSvg from '../../../../public/static/Svg/date.svg';
import TimeSvg from '../../../../public/static/Svg/time.svg';
import StatusSvg from '../../../../public/static/Svg/status.svg';
// import ActiveSvg from '../../../../public/static/Svg/active.svg';
import InActiveSvg from '../../../../public/static/Svg/inactive.svg';
import PlusSignSvg from '../../../../public/static/Svg/plus-sign.svg';
import VerifiedShieldSvg from '../../../../public/static/Svg/verified-shield.svg';
import GoogleSvg from '../../../../public/static/Svg/google.svg';
import ArrowRightSvg from '../../../../public/static/Svg/arrow-right.svg';
import MyCourseSvg from '../../../../public/static/Svg/my-course.svg';
import MessageSvg from '../../../../public/static/Svg/message.svg';
import MyAccountSvg from '../../../../public/static/Svg/my-account.svg';
import SearchSvg from '../../../../public/static/Svg/search-icon.svg';
import DownloadSvg from '../../../../public/static/Svg/download.svg';
import MiniChartSvg from '../../../../public/static/Svg/mini-chart.svg';
import ArrowDownSvg from '../../../../public/static/Svg/arrow-down.svg';
import StarSvg from '../../../../public/static/Svg/star.svg';
import ThreeDotsSvg from '../../../../public/static/Svg/three-dots.svg';
import ChatSvg from '../../../../public/static/Svg/chat.svg';
import MessageSendSvg from '../../../../public/static/Svg/send-button.svg';
import ChartLineSvg from '../../../../public/static/Svg/chart-line.svg';
import ChartPieSvg from '../../../../public/static/Svg/chart-pie.svg';
import ClarityChartLineSvg from '../../../../public/static/Svg/clarity_line-chart-outline.svg';
import PresentationChartSvg from '../../../../public/static/Svg/presentation-chart.svg';
import TrashSvg from '../../../../public/static/Svg/trash-icon.svg';
import DocumentSvg from '../../../../public/static/Svg/document.svg';
import VideoSvg from '../../../../public/static/Svg/video-icon.svg';

export const CartIcon = () => <CartSvg />;
export const CalenderIcon = () => <CalendersIcon />;
export const ContactIcon = () => <ContactsIcon />;
export const AnalyticsIcon = () => <AnalyticIcon />;
export const PublishsIcon = () => <PublishIcon />;
export const TelegramIcon = () => <TelegramSvg />;
export const SkypeIcon = () => <SkypeSvg />;
export const WhatsappIcon = () => <WhatsappSvg />;
export const MessengerIcon = () => <MessengerSvg />;
export const FacebookIcon = () => <FacebookSvg />;
export const InstaIcon = () => <InstaSvg />;
export const LinkedInIcon = () => <LinkedInSvg />;
export const TwitterIcon = () => <TwitterSvg />;
export const CameraIcon = () => <CameraPng />;
export const CrossIcon = () => <CrossSvg />;
export const UploadIcon = () => <UploadSvg />;
export const TrashIcon = () => <TrashSvg />;
export const NewEditIcon = () => <EditSvgOrange />;
export const EditDetailsIcon = () => <EditDetailsSvg />;
export const ServiceIcon = () => <ServiceSvg />;
export const StaffIcon = () => <StaffSvg />;
export const DateIcon = () => <DateSvg />;
export const TimeIcon = () => <TimeSvg />;
export const StatusIcon = () => <StatusSvg />;
export const ActiveIcon = () => <ActiveSvg />;
export const InActiveIcon = () => <InActiveSvg />;
export const PlusSign = () => <PlusSignSvg />;
export const VerifiedShield = () => <VerifiedShieldSvg />;
export const GoogleIcon = () => <GoogleSvg />;
export const RightArrowIcon = () => <ArrowRightSvg />;
export const MyCourseIcon = () => <MyCourseSvg />;
export const MessageIcon = () => <MessageSvg />;
export const MyAccountIcon = () => <MyAccountSvg />;
export const SearchIcon = () => <SearchSvg />;
export const DownloadIcon = () => <DownloadSvg />;
export const MiniChartIcon = () => <MiniChartSvg />;
export const ArrowDownIcon = () => <ArrowDownSvg />;
export const StarIcon = () => <StarSvg />;
export const ThreeDotsIcon = () => <ThreeDotsSvg />;
export const ChatIcon = () => <ChatSvg />;
export const MessageSendIcon = () => <MessageSendSvg />;
export const ChartLineIcon = () => <ChartLineSvg />;
export const ChartPieIcon = () => <ChartPieSvg />;
export const ClarityChartLineIcon = () => <ClarityChartLineSvg />;
export const PresentationChartIcon = () => <PresentationChartSvg />;
export const DocumentIcon = () => <DocumentSvg />;
export const VideoIcon = () => <VideoSvg />;
