import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/main.scss";
import Header from "@/components/AppComponents/Header/Header";
import WhatsApp from "@/components/AppComponents/WhatsApp/WhatsApp";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div style={{ paddingTop: "115px", backgroundColor: "black" }}>{children}</div>
        {/* ADD WHATSAPP NUMBER WITHOUT + SIGN */}
        <WhatsApp number={923172514024} />
        <h1>Footer</h1>
      </body>
    </html>
  );
}
